import { mkdir, writeFile, chmod } from 'fs/promises';
import { join } from 'path';

export async function generateCachehook(projectDir, cacheConfig) {
  if (!cacheConfig) return;

  const scriptsDir = join(projectDir, 'scripts');
  await mkdir(scriptsDir, { recursive: true });

  const hookPath = join(scriptsDir, 'cache-hook.sh');
  await writeFile(hookPath, generateHookScript(cacheConfig));
  await chmod(hookPath, 0o755);
}

function generateHookScript(config) {
  return `#!/bin/bash
# Fly.io Cache Hook — Agent state sharing
# Generated by claude-team-init

set -e

FLYIO_URL="${config.url}"
FLYIO_TOKEN="${config.token}"
DEFAULT_TTL=43200  # 12 hours

# ─── Helpers ─────────────────────────────────────────────────────────────────

json_escape() {
  local s="$1"
  s="\${s//\\\\/\\\\\\\\}"
  s="\${s//\\"/\\\\\\"}"
  s="\${s//\$'\\n'/\\\\n}"
  s="\${s//\$'\\r'/\\\\r}"
  s="\${s//\$'\\t'/\\\\t}"
  printf '%s' "$s"
}

_curl_cache_set() {
  local payload="$1"
  local resp
  resp=$(curl -s -w "\\n%{http_code}" --max-time 10 -X POST "$FLYIO_URL/mcp/cache-set" \\
    -H "Content-Type: application/json" \\
    -H "Authorization: Bearer $FLYIO_TOKEN" \\
    -d "$payload" 2>&1) || true

  local code="\${resp##*$'\\n'}"
  if [[ "$code" =~ ^2 ]]; then return 0; fi

  sleep 1
  resp=$(curl -s -w "\\n%{http_code}" --max-time 10 -X POST "$FLYIO_URL/mcp/cache-set" \\
    -H "Content-Type: application/json" \\
    -H "Authorization: Bearer $FLYIO_TOKEN" \\
    -d "$payload" 2>&1) || true

  code="\${resp##*$'\\n'}"
  if [[ "$code" =~ ^2 ]]; then return 0; fi
  echo "Warning: Cache write failed (HTTP $code)" >&2
  return 1
}

# ─── Cache Operations ────────────────────────────────────────────────────────

cache_set() {
  local key=$1
  local value=$2
  local ttl=\${3:-$DEFAULT_TTL}
  local original_bytes=\${4:-}
  if [[ -z "$original_bytes" || ! "$original_bytes" =~ ^[0-9]+$ ]]; then
    original_bytes=null
  fi

  local payload
  payload=$(printf '{"key":"%s","value":%s,"ttl":%s,"original_bytes":%s}' \\
    "$(json_escape "$key")" "$value" "$ttl" "$original_bytes")

  if _curl_cache_set "$payload"; then
    echo "Cached: $key"
  fi
}

cache_get() {
  curl -s -X GET "$FLYIO_URL/mcp/cache-get/$1" \\
    -H "Authorization: Bearer $FLYIO_TOKEN"
}

cache_exists() {
  local result=$(cache_get "$1" 2>/dev/null || echo "{}")
  if echo "$result" | grep -q '"value"'; then return 0; fi
  return 1
}

# ─── Specialized Operations ──────────────────────────────────────────────────

cache_build_output() {
  local status=$1 log=$2 errors=\${3:-"[]"} original_bytes=\${4:-}
  local safe_log=$(json_escape "$log")
  cache_set "build-output" "{\\"status\\":\\"$status\\",\\"timestamp\\":\\"$(date -u +'%Y-%m-%dT%H:%M:%SZ')\\",\\"log\\":\\"$safe_log\\",\\"errors\\":$errors}" "$DEFAULT_TTL" "$original_bytes"
}

cache_test_results() {
  local agent=$1 passed=$2 log=$3 original_bytes=\${4:-}
  local safe_log=$(json_escape "$log")
  cache_set "test-results-$agent" "{\\"agent\\":\\"$agent\\",\\"passed\\":$passed,\\"timestamp\\":\\"$(date -u +'%Y-%m-%dT%H:%M:%SZ')\\",\\"log\\":\\"$safe_log\\"}" "$DEFAULT_TTL" "$original_bytes"
}

log_agent_execution() {
  local agent=$1 status=$2 duration=$3 details=\${4:-"{}"}
  cache_set "agent-log-$agent" "{\\"agent\\":\\"$agent\\",\\"status\\":\\"$status\\",\\"duration_ms\\":$duration,\\"timestamp\\":\\"$(date -u +'%Y-%m-%dT%H:%M:%SZ')\\",\\"details\\":$details}" 86400
}

check_server_health() {
  local health=$(curl -s "$FLYIO_URL/health" 2>/dev/null || echo "{}")
  if echo "$health" | grep -q '"status":"ok"'; then
    echo "Cache server healthy"
    return 0
  else
    echo "Cache server unavailable"
    return 1
  fi
}

# ─── Main ────────────────────────────────────────────────────────────────────

case "\${1:-help}" in
  set)          cache_set "$2" "$3" "\${4:-$DEFAULT_TTL}" "$5" ;;
  get)          cache_get "$2" ;;
  exists)       cache_exists "$2" && echo "exists" || echo "not found" ;;
  cache-build)  cache_build_output "$2" "$3" "$4" "$5" ;;
  cache-tests)  cache_test_results "$2" "$3" "$4" "$5" ;;
  log-agent)    log_agent_execution "$2" "$3" "$4" "$5" ;;
  health)       check_server_health ;;
  *)
    echo "Cache Hook — Agent state sharing via Fly.io"
    echo ""
    echo "Usage:"
    echo "  $0 set <key> <json-value> [ttl] [original_bytes]"
    echo "  $0 get <key>"
    echo "  $0 exists <key>"
    echo "  $0 cache-build <status> <log> [errors] [original_bytes]"
    echo "  $0 cache-tests <agent> <passed> <log> [original_bytes]"
    echo "  $0 log-agent <agent> <status> <duration> [details]"
    echo "  $0 health"
    ;;
esac
`;
}
