import { mkdir, readFile, writeFile } from 'fs/promises';
import { join } from 'path';

export async function generateHooks(projectDir, audit, agentPlan, cacheConfig) {
  const claudeDir = join(projectDir, '.claude');
  await mkdir(claudeDir, { recursive: true });

  const settingsPath = join(claudeDir, 'settings.local.json');

  let settings;
  try {
    settings = JSON.parse(await readFile(settingsPath, 'utf-8'));
  } catch {
    settings = {};
  }

  // Also generate a rules.json with agent trigger rules
  await generateRules(claudeDir, audit, agentPlan);

  // Add hooks to settings — these auto-run agents on specific events
  if (!settings.hooks) settings.hooks = {};

  // After code edits → build-gate catches type errors immediately
  settings.hooks['postToolUse'] = settings.hooks['postToolUse'] || [];

  // Build-gate after Edit/Write (catches errors fast)
  settings.hooks['postToolUse'].push({
    matcher: 'Edit|Write',
    command: 'claude -p --agent build-gate --permission-mode dontAsk "Verify the build still passes after recent edits." 2>/dev/null || true',
    description: 'Auto build-gate after code edits',
    runInBackground: true,
  });

  // After git commit → run the validation pipeline
  settings.hooks['postToolUse'].push({
    matcher: 'Bash:*git commit*',
    command: buildPostCommitPipeline(agentPlan, cacheConfig),
    description: 'Post-commit agent validation pipeline',
    runInBackground: true,
  });

  await writeFile(settingsPath, JSON.stringify(settings, null, 2) + '\n');
}

function buildPostCommitPipeline(agentPlan, cacheConfig) {
  // Sequential pipeline: build → regression → specialists → qa-signoff
  const stages = ['build-gate', 'regression-checker'];

  const specialistNames = agentPlan.map(a => a.name);
  if (specialistNames.includes('security-reviewer')) stages.push('security-reviewer');
  if (specialistNames.includes('api-prober')) stages.push('api-prober');

  // qa-signoff always last
  stages.push('qa-signoff');

  const cmds = stages.map(a =>
    `claude -p --agent ${a} --permission-mode dontAsk "Validate the latest commit." 2>/dev/null || true`
  );

  return cmds.join(' && ');
}

async function generateRules(claudeDir, audit, agentPlan) {
  const rulesPath = join(claudeDir, 'rules.json');

  // Don't overwrite existing rules
  try {
    await readFile(rulesPath);
    return;
  } catch {
    // Doesn't exist, create it
  }

  const agentNames = agentPlan.map(a => a.name);

  const rules = {
    version: 1,
    description: 'Agent trigger rules generated by claude-team-init. Defines when agents auto-activate based on file changes.',
    rules: [],
  };

  // Rule 1: Build-gate required for all source changes
  const srcExtensions = {
    'JavaScript/TypeScript': '**/*.{ts,tsx,js,jsx,mjs}',
    'Python': '**/*.py',
    'Ruby': '**/*.rb',
    'Go': '**/*.go',
    'Rust': '**/*.rs',
    'Swift': '**/*.swift',
    'Dart': '**/*.dart',
    'Java/Kotlin': '**/*.{java,kt}',
    'PHP': '**/*.php',
    'Elixir': '**/*.{ex,exs}',
  };

  const srcPattern = srcExtensions[audit.language] || '**/*.{ts,tsx,js,jsx}';

  rules.rules.push({
    id: 'auto-build-gate',
    title: 'Build Gate on Source Changes',
    scope: {
      triggersOn: [`Any change to ${srcPattern}`],
      doesNotTriggerOn: ['Comment-only changes', 'Type-only edits', 'README/docs changes'],
    },
    action: {
      agent: 'build-gate',
      blocking: false,
      description: 'Automatically verify the build passes after source code changes',
    },
  });

  // Rule 2: Security reviewer on DB/auth changes
  if (agentNames.includes('security-reviewer') && audit.database) {
    const dbTriggers = [];
    if (audit.database === 'Supabase') {
      dbTriggers.push('Any change to supabase/**', 'Any change to **/migrations/**');
    }
    if (audit.database === 'Prisma') {
      dbTriggers.push('Any change to prisma/**');
    }
    dbTriggers.push('Any change to **/*auth*', 'Any change to **/*policy*', 'Any change to **/*permission*');

    rules.rules.push({
      id: 'auto-security-review',
      title: `Security Review on ${audit.database} Changes`,
      scope: {
        triggersOn: dbTriggers,
      },
      action: {
        agent: 'security-reviewer',
        blocking: true,
        description: `Auto-trigger security review when ${audit.database} schemas or auth code changes`,
      },
    });
  }

  // Rule 3: Mobile expert on API changes (if mobile exists)
  if (agentNames.includes('mobile-expert') && audit.hasApi) {
    rules.rules.push({
      id: 'auto-mobile-compat',
      title: 'Mobile Compatibility on API Changes',
      scope: {
        triggersOn: [
          'Any change to **/api/**',
          'Any change to **/routes/**',
          'Any change to **/controllers/**',
        ],
      },
      action: {
        agent: 'mobile-expert',
        blocking: false,
        description: 'Check that API changes don\'t break mobile clients',
      },
    });
  }

  // Rule 4: Auth verifier on auth changes
  if (agentNames.includes('auth-verifier') && audit.auth) {
    rules.rules.push({
      id: 'auto-auth-verify',
      title: `Auth Verification on ${audit.auth} Changes`,
      scope: {
        triggersOn: [
          'Any change to **/*auth*',
          'Any change to **/*session*',
          'Any change to **/*login*',
          'Any change to **/*signup*',
          'Any change to **/middleware*',
        ],
      },
      action: {
        agent: 'auth-verifier',
        blocking: true,
        description: `Auto-verify auth flows when ${audit.auth} code changes`,
      },
    });
  }

  // Rule 5: Billing bot on payment changes
  if (agentNames.includes('billing-bot') && audit.payments) {
    rules.rules.push({
      id: 'auto-billing-check',
      title: `Billing Check on ${audit.payments} Changes`,
      scope: {
        triggersOn: [
          'Any change to **/*billing*',
          'Any change to **/*payment*',
          'Any change to **/*subscription*',
          'Any change to **/*webhook*',
          'Any change to **/*stripe*',
          'Any change to **/*checkout*',
        ],
      },
      action: {
        agent: 'billing-bot',
        blocking: true,
        description: `Auto-verify payment logic when ${audit.payments} code changes`,
      },
    });
  }

  // Rule 6: Crypto auditor on encryption changes
  if (agentNames.includes('crypto-auditor') && audit.hasCrypto) {
    rules.rules.push({
      id: 'auto-crypto-audit',
      title: 'Crypto Audit on Encryption Changes',
      scope: {
        triggersOn: [
          'Any change to **/*crypto*',
          'Any change to **/*encrypt*',
          'Any change to **/*decrypt*',
          'Any change to **/*cipher*',
          'Any change to **/*key*',
        ],
      },
      action: {
        agent: 'crypto-auditor',
        blocking: true,
        description: 'Auto-audit when encryption code changes',
      },
    });
  }

  // Rule 7: Regression checker always after qa-signoff approves
  rules.rules.push({
    id: 'post-commit-pipeline',
    title: 'Post-Commit Validation Pipeline',
    scope: {
      triggersOn: ['Any git commit'],
    },
    action: {
      pipeline: ['build-gate', 'regression-checker', 'qa-signoff'],
      description: 'Sequential validation after every commit: build → tests → QA signoff',
    },
  });

  await writeFile(rulesPath, JSON.stringify(rules, null, 2) + '\n');
}
