import { mkdir, writeFile, chmod } from 'fs/promises';
import { join } from 'path';

export async function generateLauncher(projectDir, audit, cacheConfig) {
  const scriptsDir = join(projectDir, 'scripts');
  await mkdir(scriptsDir, { recursive: true });

  const launcherPath = join(scriptsDir, 'team-launch.sh');
  await writeFile(launcherPath, generateLauncherScript(projectDir, cacheConfig));
  await chmod(launcherPath, 0o755);
}

function generateLauncherScript(projectDir, cacheConfig) {
  const cacheUrl = cacheConfig?.url || '';
  const cacheToken = cacheConfig?.token || '';
  const hookCmd = cacheConfig ? 'scripts/cache-hook.sh' : '';

  return `#!/bin/bash
# Team Launch — Spawn parallel orchestrator sessions in tmux
# Generated by claude-team-init

set -euo pipefail

REPO="${projectDir}"
TMUX_SESSION="agents"
WINDOW_OFFSET=10
MONITOR_INTERVAL=30
${cacheConfig ? `CACHE_HOOK="$REPO/scripts/cache-hook.sh"
FLYIO_URL="${cacheUrl}"
FLYIO_TOKEN="${cacheToken}"` : ''}

RED='\\033[0;31m'; GREEN='\\033[0;32m'; YELLOW='\\033[1;33m'
CYAN='\\033[0;36m'; BOLD='\\033[1m'; NC='\\033[0m'

log()  { echo -e "\${CYAN}[team-launch]\${NC} $*"; }
ok()   { echo -e "\${GREEN}[team-launch]\${NC} $*"; }
warn() { echo -e "\${YELLOW}[team-launch]\${NC} $*"; }
err()  { echo -e "\${RED}[team-launch]\${NC} $*" >&2; }

gen_sid() {
  local n=$1
  local uuid
  uuid=$(uuidgen 2>/dev/null || cat /proc/sys/kernel/random/uuid 2>/dev/null || echo "$$-$RANDOM")
  echo "team-\${n}-$(echo "$uuid" | tr '[:upper:]' '[:lower:]' | cut -c1-8)"
}

check_prerequisites() {
  if ! command -v claude &>/dev/null; then
    err "claude CLI not found. Install Claude Code first."
    exit 1
  fi
  if ! command -v tmux &>/dev/null; then
    err "tmux not found. Install with: brew install tmux"
    exit 1
  fi
${cacheConfig ? '  $CACHE_HOOK health &>/dev/null || warn "Cache server unreachable — agents will run without shared cache"' : ''}
}

launch_orchestrators() {
  local problems=("$@")
  local count=\${#problems[@]}

  log "Launching \${BOLD}\${count}\${NC} orchestrator(s)..."

  if ! tmux has-session -t "$TMUX_SESSION" 2>/dev/null; then
    tmux new-session -d -s "$TMUX_SESSION" -x 200 -y 50 -c "$REPO"
  fi

  local sids=()
  for i in $(seq 1 "$count"); do sids+=("$(gen_sid "$i")"); done
${cacheConfig ? `
  # Write manifest to cache
  local manifest='{"sessions":['
  for i in $(seq 0 $((count - 1))); do
    local escaped=$(echo "\${problems[$i]}" | sed 's/\\\\/\\\\\\\\/g; s/"/\\\\"/g' | tr '\\n' ' ')
    [ "$i" -gt 0 ] && manifest+=','
    manifest+="{\\"id\\":\\"\${sids[$i]}\\",\\"problem\\":\\"$escaped\\"}"
  done
  manifest+="]}"
  $CACHE_HOOK set "team-launch-$(date +%s)" "$manifest" 43200 2>/dev/null || true
` : ''}
  for i in $(seq 0 $((count - 1))); do
    local sid="\${sids[$i]}"
    local problem="\${problems[$i]}"
    local window_name="orch-$((i + 1))"
    local window_idx=$((WINDOW_OFFSET + i))

    log "  Window \${BOLD}\${window_name}\${NC} (\${sid}): $(echo "$problem" | head -c 60)..."

    tmux new-window -t "\${TMUX_SESSION}:\${window_idx}" -n "$window_name" -c "$REPO" 2>/dev/null || \\
      tmux new-window -t "\${TMUX_SESSION}" -n "$window_name" -c "$REPO"

    tmux set-window-option -t "\${TMUX_SESSION}:\${window_name}" remain-on-exit on 2>/dev/null || true

    tmux send-keys -t "\${TMUX_SESSION}:\${window_name}" \\
      "cd \${REPO} && claude --agent orchestrator --permission-mode dontAsk --worktree \${sid} --append-system-prompt 'SESSION_ID=\${sid}' -p '\${problem//\\'/\\\\'\\'\\\\'}' 2>&1 | tee /tmp/orch-\${sid}.log; echo '--- ORCHESTRATOR \${sid} FINISHED ---'" Enter
  done

  echo ""
  ok "All \${count} orchestrator(s) launched!"
  echo ""
  log "Switch to window:  \${BOLD}Ctrl+B \${WINDOW_OFFSET}\${NC}  (orch-1)"
  log "Cleanup windows:   \${BOLD}$0 --cleanup\${NC}"
}

cleanup_windows() {
  log "Cleaning up..."
  local cleaned=0
  for window in $(tmux list-windows -t "$TMUX_SESSION" -F '#{window_name}' 2>/dev/null || echo ""); do
    if [[ "$window" == orch-* ]]; then
      tmux kill-window -t "\${TMUX_SESSION}:\${window}" 2>/dev/null && ((cleaned++)) || true
    fi
  done

  # Clean up worktrees
  cd "$REPO"
  for wt in $(git worktree list --porcelain 2>/dev/null | grep '^worktree ' | awk '{print $2}'); do
    local wt_name=$(basename "$wt")
    if [[ "$wt_name" == team-* ]]; then
      git worktree remove --force "$wt" 2>/dev/null || true
      ((cleaned++))
    fi
  done
  git worktree prune 2>/dev/null || true

  [ "$cleaned" -gt 0 ] && ok "Cleaned up \${cleaned} item(s)" || log "Nothing to clean up"
  rm -f /tmp/orch-team-*.log 2>/dev/null || true
}

usage() {
  cat << 'USAGE'
Team Launch — Parallel Orchestrator Sessions

Usage:
  team-launch.sh "problem 1" "problem 2" ...    Launch orchestrators
  team-launch.sh -f problems.txt                Load from file
  team-launch.sh --cleanup                      Remove orchestrator windows + worktrees
  team-launch.sh --help                         Show this help

Each orchestrator generates 3 solutions, validates each, and iterates
until 97% confidence (92% acceptable after 5 rounds).
USAGE
}

case "\${1:-}" in
  --help|-h) usage; exit 0 ;;
  --cleanup) cleanup_windows; exit 0 ;;
  -f)
    [ -z "\${2:-}" ] || [ ! -f "$2" ] && { err "File not found: \${2:-<none>}"; exit 1; }
    check_prerequisites
    problems=()
    while IFS= read -r line; do
      line=$(echo "$line" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
      [ -n "$line" ] && [[ ! "$line" =~ ^# ]] && problems+=("$line")
    done < "$2"
    [ \${#problems[@]} -eq 0 ] && { err "No problems in $2"; exit 1; }
    launch_orchestrators "\${problems[@]}"
    ;;
  "") usage; exit 1 ;;
  *) check_prerequisites; launch_orchestrators "$@" ;;
esac
`;
}
