import { mkdir, readFile, writeFile, chmod } from 'fs/promises';
import { join } from 'path';

export async function generateStatusline(projectDir, audit, cacheConfig) {
  const claudeDir = join(projectDir, '.claude');
  const scriptsDir = join(projectDir, 'scripts');
  await mkdir(claudeDir, { recursive: true });
  await mkdir(scriptsDir, { recursive: true });

  const scriptPath = join(scriptsDir, 'vibe-statusline.sh');
  await writeFile(scriptPath, buildStatuslineScript(cacheConfig));
  await chmod(scriptPath, 0o755);

  const settingsPath = join(claudeDir, 'settings.local.json');
  let settings;
  try {
    settings = JSON.parse(await readFile(settingsPath, 'utf-8'));
  } catch {
    settings = {};
  }

  if (settings.statusLine) return; // respect user-configured statusline

  settings.statusLine = {
    type: 'command',
    command: './scripts/vibe-statusline.sh',
  };

  await writeFile(settingsPath, JSON.stringify(settings, null, 2) + '\n');
}

function buildStatuslineScript(hasCache) {
  const cacheBlock = hasCache
    ? `
  build=$(scripts/cache-hook.sh get build-output 2>/dev/null \\
            | grep -o '"status":"[^"]*"' | head -1 | cut -d'"' -f4)
  build=\${build:-?}
  if scripts/cache-hook.sh health 2>/dev/null | grep -q healthy; then
    cache="on"
  else
    cache="off"
  fi
`
    : `
  build="?"
  cache="-"
`;

  return `#!/bin/bash
# vibe-crew statusline — generated by claude-team-init
# Claude Code pipes a JSON payload on stdin; we print a single status line.

set -u

payload=$(cat)
model=$(printf '%s' "$payload" | sed -n 's/.*"display_name":"\\([^"]*\\)".*/\\1/p' | head -1)
model=\${model:-Claude}

cwd=$(basename "$(pwd)")
branch=$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo "-")

dirty=""
if [ -n "$(git status --porcelain 2>/dev/null)" ]; then
  dirty="*"
fi
${cacheBlock}
printf '[%s] %s  %s%s  build:%s  cache:%s' \\
  "$model" "$cwd" "$branch" "$dirty" "$build" "$cache"
`;
}
